// Copyright The EntID Authors.
// SPDX-License-Identifier: Apache-2.0

package main

import (
	"crypto/sha256"
	"encoding/hex"
	"flag"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// This command is what stands between an untrusted bundle and the source the
// engine ships. Its checks ran on every build and were covered by none of them.

func TestLockValue(t *testing.T) {
	const lock = `# a comment mentioning rules_sha256 = "not this one"

rules_version = "2026.08.31"
  rules_sha256   =   "abc123"
malformed line without an equals sign
empty_value = ""
`
	for _, tc := range []struct {
		key     string
		want    string
		wantErr bool
	}{
		{key: "rules_version", want: "2026.08.31"},
		{key: "rules_sha256", want: "abc123"},
		{key: "empty_value", want: ""},
		{key: "absent_key", wantErr: true},
	} {
		got, err := lockValue(lock, tc.key)
		if tc.wantErr {
			if err == nil {
				t.Errorf("%s: expected an error, got %q", tc.key, got)
			}
			continue
		}
		if err != nil {
			t.Errorf("%s: %v", tc.key, err)
			continue
		}
		if got != tc.want {
			t.Errorf("%s: got %q, want %q", tc.key, got, tc.want)
		}
	}
}

func TestVerifyLock(t *testing.T) {
	bundle := []byte("not really a bundle, but it has a digest")
	sum := sha256.Sum256(bundle)
	digest := hex.EncodeToString(sum[:])

	write := func(t *testing.T, content string) string {
		t.Helper()
		path := filepath.Join(t.TempDir(), "rules.lock")
		if err := os.WriteFile(path, []byte(content), 0o600); err != nil {
			t.Fatal(err)
		}
		return path
	}

	t.Run("a matching digest passes", func(t *testing.T) {
		if err := verifyLock(write(t, `rules_sha256 = "`+digest+`"`), bundle); err != nil {
			t.Fatal(err)
		}
	})

	t.Run("a different digest is refused", func(t *testing.T) {
		err := verifyLock(write(t, `rules_sha256 = "`+strings.Repeat("0", 64)+`"`), bundle)
		if err == nil {
			t.Fatal("a bundle that does not match the lock must not generate")
		}
		if !strings.Contains(err.Error(), digest) {
			t.Fatalf("the diagnostic must name what was measured: %v", err)
		}
	})

	t.Run("a lock declaring no digest is refused", func(t *testing.T) {
		if err := verifyLock(write(t, `rules_version = "2026.08.31"`), bundle); err == nil {
			t.Fatal("a lock with no rules_sha256 must not generate")
		}
	})

	t.Run("a lock that cannot be read is refused", func(t *testing.T) {
		if err := verifyLock(filepath.Join(t.TempDir(), "absent.lock"), bundle); err == nil {
			t.Fatal("a missing lock must not generate")
		}
	})
}

// callRun invokes run with a fresh flag set, since run declares its flags on
// the command line set and a second declaration would panic.
func callRun(t *testing.T, args ...string) error {
	t.Helper()
	oldArgs, oldFlags := os.Args, flag.CommandLine
	t.Cleanup(func() { os.Args, flag.CommandLine = oldArgs, oldFlags })
	flag.CommandLine = flag.NewFlagSet("entid-gen", flag.ContinueOnError)
	flag.CommandLine.SetOutput(os.Stderr)
	os.Args = append([]string{"entid-gen"}, args...)
	return run()
}

func TestRunGeneratesFromTheShippedBundle(t *testing.T) {
	out := filepath.Join(t.TempDir(), "rules_gen.go")
	err := callRun(t,
		"-bundle", filepath.Join("..", "..", "spec", "entid-rules.binpb"),
		"-lock", filepath.Join("..", "..", "rules.lock"),
		"-out", out,
		"-package", "entid",
	)
	if err != nil {
		t.Fatalf("the shipped bundle must generate: %v", err)
	}
	src, err := os.ReadFile(out)
	if err != nil {
		t.Fatal(err)
	}
	// The marker Go recognises has to precede the package clause, or tooling
	// treats the file as hand written.
	marker := strings.Index(string(src), "// Code generated by entid-gen")
	clause := strings.Index(string(src), "package entid")
	if marker < 0 {
		t.Fatal("the output does not carry the generated marker")
	}
	if clause < 0 {
		t.Fatal("the output does not declare the package it was asked for")
	}
	if marker > clause {
		t.Fatal("the generated marker must come before the package clause")
	}
	if !strings.Contains(string(src), "DO NOT EDIT.") {
		t.Fatal("the generated marker is not in the form Go recognises")
	}
}

func TestRunRefusesWhatItCannotGenerate(t *testing.T) {
	dir := t.TempDir()
	lock := filepath.Join("..", "..", "rules.lock")
	shipped := filepath.Join("..", "..", "spec", "entid-rules.binpb")

	t.Run("a bundle that does not exist", func(t *testing.T) {
		err := callRun(t, "-bundle", filepath.Join(dir, "absent.binpb"), "-lock", lock,
			"-out", filepath.Join(dir, "a.go"))
		if err == nil || !strings.Contains(err.Error(), "read the bundle") {
			t.Fatalf("got %v", err)
		}
	})

	t.Run("a bundle the lock does not attest", func(t *testing.T) {
		forged := filepath.Join(dir, "forged.binpb")
		if err := os.WriteFile(forged, []byte{0x08, 0x01}, 0o600); err != nil {
			t.Fatal(err)
		}
		err := callRun(t, "-bundle", forged, "-lock", lock, "-out", filepath.Join(dir, "b.go"))
		if err == nil || !strings.Contains(err.Error(), "digest") {
			t.Fatalf("got %v", err)
		}
	})

	t.Run("a bundle the loader refuses", func(t *testing.T) {
		// A bundle whose digest matches a lock written for it, so the refusal
		// comes from the loader rather than from the attestation.
		forged := []byte{0x08, 0x63} // format_version 99
		sum := sha256.Sum256(forged)
		bundlePath := filepath.Join(dir, "unsupported.binpb")
		lockPath := filepath.Join(dir, "unsupported.lock")
		if err := os.WriteFile(bundlePath, forged, 0o600); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(lockPath,
			[]byte(`rules_sha256 = "`+hex.EncodeToString(sum[:])+`"`), 0o600); err != nil {
			t.Fatal(err)
		}
		err := callRun(t, "-bundle", bundlePath, "-lock", lockPath,
			"-out", filepath.Join(dir, "c.go"))
		if err == nil || !strings.Contains(err.Error(), "refusing to generate") {
			t.Fatalf("got %v", err)
		}
	})

	t.Run("an output path that cannot be written", func(t *testing.T) {
		err := callRun(t, "-bundle", shipped, "-lock", lock,
			"-out", filepath.Join(dir, "no-such-directory", "d.go"))
		if err == nil || !strings.Contains(err.Error(), "write") {
			t.Fatalf("got %v", err)
		}
	})
}
